### PR TITLE
Made error messages less informative

### PR DESCRIPTION
**Pull request by Helios-fr**
#22

### CODE REVIEW

**Comment by Helios-fr** [comment]
@SebastianBilek @ArchieHickmott

**Comment by Helios-fr** [comment]
Since the email is in use needs to be displayed on register, this is not really a security vulnerability in the first place, since the only piece of information that should be able to cause an error on registration is the email.

**Review by ArchieHickmott — CHANGES_REQUESTED** [review]
Change line 232 to be form.**password**.errors.append(...) instead of email. It will display under email if the email doesn't exist and display under password if it doesn't exist

**Comment by Helios-fr** [comment]
Fixed @ArchieHickmott

**Review by ArchieHickmott — APPROVED** [review]

**Pull request merged**
